<?php
/**
 * @file
 * Main bootstrap file of the fabric_canvas_view module.
 */

function get_svg(){
	$animals= drupal_get_path("module", "fabric_canvas_view").'/svg/animals';
	
	$scanned_directory = array_diff(scandir($animals), array('..', '.'));

	drupal_add_js(array('canvas_view' => array("svg_items" => array("animals" => $scanned_directory ))), 'setting');
	
	$borders= drupal_get_path("module", "fabric_canvas_view").'/svg/borders';
	
	$scanned_directory = array_diff(scandir($borders), array('..', '.'));

	drupal_add_js(array('canvas_view' => array("svg_items" => array("borders" => $scanned_directory ))), 'setting');
	
}
//get field contents for canvas
/* function fabric_canvas_view_preprocess_field(&$variables) {
	
	if(isset($variables["element"]["#field_type"])){
		if($variables["element"]["#field_type"] === "text_with_summary"){
			$out = [];
			foreach ($variables["element"]["#items"] as $k => $item){
				$out[] = array("title" => $item["safe_value"], "field_name" => $variables["element"]["#field_name"] , "type" => "text_with_summary");
			}
		}
		/* if($variables["element"]["#field_type"] === "entityreference"){
			$out = [];
		foreach ($variables["element"]["#items"] as $k => $item){
		$node_ref =  node_load($item["target_id"]);
		$out[] = array("title" => $node_ref->title, "field_name" => $variables["element"]["#field_name"] ,"type" => "entityreference");

		}
		drupal_add_js(array('canvas_view' =>  array("text_items" => $out)), 'setting');
		} */
	/* }
	if($variables["element"]["#field_type"] === "image"){
		$out = [];
		foreach ($variables["element"]["#items"] as $k => $item){
			$url = file_create_url($item['uri']);

			$out[] = array("filename" => $item["filename"],"fid" =>  $item["fid"], "src" => $url, "field_name" => $variables["element"]["#field_name"] ,"type" => "image");

		}
		drupal_add_js(array('canvas_view' =>  array("image_items" => $out)), 'setting');

	}

} */
 
function fabric_canvas_view_menu() {
  $menu = array();

  $menu['file_upload_handler'] = array(
    'title' => 'file_upload_handler',
    //'page callback' => 'file_upload_handler',
    'page callback' => '_save_upload',
    'access callback' => 'file_upload_handler_access',
    'file' => 'fabric_canvas_view.pages.inc',
     'delivery callback' => '_deliver_page',
    'type' => MENU_CALLBACK,
    'weight' => 0,
  );

  $menu['save_canvas_handler'] = array(
    'title' => 'file_upload_handler',
    'page callback' => 'save_canvas_handler',
    //'page arguments' => array(2),
    'access callback' => 'file_upload_handler_access',
    'file' => 'fabric_canvas_view.pages.inc',
	'delivery callback' => '_deliver_page',
    'type' => MENU_CALLBACK,
    'weight' => 0,
  );

  $menu['uri_2_url/%'] = array(
  		'title' => 'file_upload_handler',
  		'page callback' => '_uri_2_url',
  		'page arguments' => array(1),
  		'access callback' => 'file_upload_handler_access',
  		'file' => 'fabric_canvas_view.pages.inc',
  		'delivery callback' => '_deliver_page',
  		'type' => MENU_CALLBACK,
  		'weight' => 0,
  );
  $menu['delete_fid/%/%'] = array(
  		'title' => 'file_upload_handler',
  		'page callback' => '_delete_fid',
  		'page arguments' => array(1,2),
  		'access callback' => 'file_upload_handler_access',
  		'file' => 'fabric_canvas_view.pages.inc',
  		'delivery callback' => '_deliver_page',
  		'type' => MENU_CALLBACK,
  		'weight' => 0,
  );
  
  return $menu;
}
function _deliver_page($page_callback_result) {
// $page_callback_result;
  drupal_exit();
}
function file_upload_handler_access() {
  return TRUE;
}

function fabric_canvas_view_file_download(){
	//return array();
	return null;
}
